### ISSUE TITLE
Create Slack account when user registers

### ISSUE THREAD

**Issue by emanuelen5** [makerspace/makeradmin#283]

**Comment by GenuineAster** [comment]
This would be super cool because we can pre-fill member numbers on Slack users and automatically associate Slack users to MakerAdmin users, making it easier to find who to reach when we need to contact someone about things. It would also allow us to automate the invite process making Slack way more obvious for non-technical or less information-hungry members. 👍

**Comment by emanuelen5** [comment]
> The invite request management APIs may only be used by Enterprise Grid orgs.

Source: https://api.slack.com/admins/inviting
