### ISSUE TITLE
Show invite link to Slack (only) when you are a lab member

### ISSUE THREAD

**Issue by emanuelen5** [makerspace/makeradmin#286]

**Comment by GenuineAster** [comment]
To add some info here, Slack APIs for inviting members are only available on enterprise workspaces so we can't use those. Instead we can send a workspace invite link to new members and/or display the Slack URL during sign up, instead of using launchpass to send the invite.

New members find it too difficult to sign up for Slack and so we don't get that many people from our non-technical membership in Slack, meaning those people are usually not informed of what's going on in the space and they don't have a way to participate in discussions.

Additionally, we don't push Slack very hard in the sign-up process and there are talks on possibly making it mandatory for new members that will take place in the next board meeting.

So we'd generally like to simplify/automate the Slack signup process for new members and try as hard as possible to get them involved there.

**Comment by GenuineAster** [comment]
The title changed while I was writing. I think all förening members should have access to Slack regardless of lab access. It is the makerspace slack, not the makerspace lab slack.

**Comment by ceejii** [comment]
Not quite sure if I understand the idea correctly and don't know what an implementation of it might be like exactly. Since I don't know for sure what is planned, this is my attempt to establish a boundary for what is acceptable, for me.Personally I would be unhappy if an organization would share my email address in any way with another company, at least without my explicit and clear approval. I'd also really want to be able to at least opt out of that flow in order to sign up myself instead. I'm not at all accepting of my contact information being shared between organizations. I want to continue to have control over what address I give out to each organization/company I have a relation with.Den 5 juni 2023 18:07 skrev Mischa Alff ***@***.***>:
The title changed while I was writing. I think all förening members should have access to Slack regardless of lab access. It is the makerspace slack, not the makerspace lab slack.

**Comment by GenuineAster** [comment]
Fortunately, we can't share emails anyways, so we have to just share a link with the member instead.

**Comment by emanuelen5** [comment]
I would argue that this is completed since we show the invite link in the signup flow
