### ISSUE TITLE
Consider not sending updated_member_info for admin updates

### ISSUE THREAD

**Issue by nitro2k01** [makerspace/makeradmin#542]
I just edited a member account and noticed that a updated_member_info e-mail was sent. This may be inappropriate for admin updates, for example if the old address was incorrect so you don't want notifications sent to someone who is not the actual member, or if editing a member that's being suspended where you may not want to reveal in that way that an admin is editing something about the account.

**Comment by emanuelen5** [comment]
I believe we should keep this as it is because it offers several key benefits:

   1. **Informs the previous email owner:** The former owner will have already received messages from Makeradmin, so this serves as a clear update for them.
   1. **Reduces the risk of being flagged as spam:** Sending a notification about the email removal reassures the previous owner and helps prevent spam reports.
   1. **Validates the update:** The confirmation email allows the admin to verify that the email update has been made correctly.
   1. **Ensures accountability:** It prevents admins from making email changes without any oversight.

Finally, I think suspension should be managed through a completely separate mechanism, which would require its own feature request.

**Comment by emanuelen5** [comment]
And the feature request is, as least partially, covered by #386
